"""Seed templates catalog for CineReel AI."""

TEMPLATES = [
    {
        "template_id": "tpl_cine_product_launch",
        "title": "Cinematic Product Launch",
        "category": "Cinematic Ads",
        "video_type": "cinematic_ad",
        "aspect_ratio": "16:9",
        "duration_sec": 30,
        "description": "Hero shot with slow dolly-in, golden-hour reveal and bold CTA.",
        "thumbnail": "https://images.pexels.com/photos/13812458/pexels-photo-13812458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_ig_reel_hook",
        "title": "Instagram Reel — Hook + Story",
        "category": "Instagram Reels",
        "video_type": "ig_reel",
        "aspect_ratio": "9:16",
        "duration_sec": 30,
        "description": "Pattern-interrupt hook, fast cuts, captions baked in.",
        "thumbnail": "https://images.pexels.com/photos/3062541/pexels-photo-3062541.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_yt_short_explainer",
        "title": "YouTube Short Explainer",
        "category": "YouTube Shorts",
        "video_type": "yt_short",
        "aspect_ratio": "9:16",
        "duration_sec": 45,
        "description": "Quick explainer with avatar host and B-roll overlays.",
        "thumbnail": "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_tiktok_pov",
        "title": "TikTok POV Story",
        "category": "TikTok",
        "video_type": "tiktok",
        "aspect_ratio": "9:16",
        "duration_sec": 20,
        "description": "Trend-ready POV with subtitle animation and pop-music feel.",
        "thumbnail": "https://images.pexels.com/photos/3756879/pexels-photo-3756879.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_realestate_walkthrough",
        "title": "Real Estate Walkthrough",
        "category": "Real Estate",
        "video_type": "real_estate",
        "aspect_ratio": "16:9",
        "duration_sec": 45,
        "description": "Smooth gimbal-style tour with feature callouts.",
        "thumbnail": "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": True,
    },
    {
        "template_id": "tpl_avatar_news",
        "title": "AI News Anchor",
        "category": "AI News",
        "video_type": "ai_news",
        "aspect_ratio": "16:9",
        "duration_sec": 60,
        "description": "Talking avatar reads news with on-screen lower thirds.",
        "thumbnail": "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": True,
    },
    {
        "template_id": "tpl_ecom_product",
        "title": "E-commerce Product Spotlight",
        "category": "E-commerce",
        "video_type": "product_ad",
        "aspect_ratio": "1:1",
        "duration_sec": 15,
        "description": "Loop-ready square ad — product turntable + benefits.",
        "thumbnail": "https://images.pexels.com/photos/1666065/pexels-photo-1666065.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_app_promo",
        "title": "App Promotion",
        "category": "App Promotion",
        "video_type": "app_promo",
        "aspect_ratio": "9:16",
        "duration_sec": 30,
        "description": "Phone mockups, UI motion, and store-CTA close.",
        "thumbnail": "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_business_promo",
        "title": "Business Promotion",
        "category": "Business",
        "video_type": "business_promo",
        "aspect_ratio": "16:9",
        "duration_sec": 45,
        "description": "Corporate-clean style with brand colour overlays.",
        "thumbnail": "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_education",
        "title": "Educational Explainer",
        "category": "Educational",
        "video_type": "educational",
        "aspect_ratio": "16:9",
        "duration_sec": 60,
        "description": "Slide-style explainer with avatar narration.",
        "thumbnail": "https://images.pexels.com/photos/5905885/pexels-photo-5905885.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": False,
    },
    {
        "template_id": "tpl_motivation",
        "title": "Motivational Cinematic",
        "category": "Cinematic Ads",
        "video_type": "cinematic_ad",
        "aspect_ratio": "9:16",
        "duration_sec": 30,
        "description": "Epic-cinematic visuals with motivational voiceover.",
        "thumbnail": "https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": True,
    },
    {
        "template_id": "tpl_talking_avatar",
        "title": "Talking Avatar — Pitch",
        "category": "Talking Avatar",
        "video_type": "talking_avatar",
        "aspect_ratio": "9:16",
        "duration_sec": 30,
        "description": "AI human host pitches your product with lip sync.",
        "thumbnail": "https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=940",
        "is_premium": True,
    },
]


VIDEO_TYPES = [
    {"id": "cinematic_ad", "name": "Cinematic Ad", "icon": "film", "default_ratio": "16:9"},
    {"id": "product_ad", "name": "Product Ad", "icon": "package", "default_ratio": "1:1"},
    {"id": "talking_avatar", "name": "Talking Avatar", "icon": "user-square", "default_ratio": "9:16"},
    {"id": "yt_short", "name": "YouTube Short", "icon": "youtube", "default_ratio": "9:16"},
    {"id": "ig_reel", "name": "Instagram Reel", "icon": "instagram", "default_ratio": "9:16"},
    {"id": "tiktok", "name": "TikTok Video", "icon": "music", "default_ratio": "9:16"},
    {"id": "educational", "name": "Educational", "icon": "book-open", "default_ratio": "16:9"},
    {"id": "business_promo", "name": "Business Promo", "icon": "briefcase", "default_ratio": "16:9"},
    {"id": "ai_news", "name": "AI News", "icon": "newspaper", "default_ratio": "16:9"},
    {"id": "real_estate", "name": "Real Estate", "icon": "home", "default_ratio": "16:9"},
    {"id": "app_promo", "name": "App Promotion", "icon": "smartphone", "default_ratio": "9:16"},
    {"id": "ecom_ad", "name": "E-commerce Ad", "icon": "shopping-bag", "default_ratio": "1:1"},
]


AVATARS = [
    {"id": "avatar_aanya", "name": "Aanya", "gender": "female", "style": "indian-professional",
     "thumbnail": "https://images.pexels.com/photos/31869537/pexels-photo-31869537.jpeg?auto=compress&cs=tinysrgb&w=400"},
    {"id": "avatar_arjun", "name": "Arjun", "gender": "male", "style": "indian-casual",
     "thumbnail": "https://images.pexels.com/photos/36623225/pexels-photo-36623225.jpeg?auto=compress&cs=tinysrgb&w=400"},
    {"id": "avatar_sophia", "name": "Sophia", "gender": "female", "style": "western-business",
     "thumbnail": "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400"},
    {"id": "avatar_marcus", "name": "Marcus", "gender": "male", "style": "western-anchor",
     "thumbnail": "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400"},
    {"id": "avatar_riya", "name": "Riya", "gender": "female", "style": "youthful-genz",
     "thumbnail": "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=400"},
    {"id": "avatar_dev", "name": "Dev", "gender": "male", "style": "founder-pitch",
     "thumbnail": "https://images.pexels.com/photos/3778603/pexels-photo-3778603.jpeg?auto=compress&cs=tinysrgb&w=400"},
]


STOCK_ASSETS = {
    "images": [
        "https://images.pexels.com/photos/13812458/pexels-photo-13812458.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/3062541/pexels-photo-3062541.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/1666065/pexels-photo-1666065.jpeg?auto=compress&cs=tinysrgb&w=940",
        "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=940",
    ],
    "music": [
        {"id": "m_uplifting", "title": "Uplifting Cinematic", "mood": "uplifting", "duration": 120},
        {"id": "m_epic", "title": "Epic Trailer", "mood": "epic", "duration": 90},
        {"id": "m_lofi", "title": "Lo-Fi Chill", "mood": "lofi", "duration": 180},
        {"id": "m_corporate", "title": "Corporate Clean", "mood": "corporate", "duration": 120},
        {"id": "m_indian_fusion", "title": "Indian Fusion", "mood": "indian", "duration": 150},
    ],
    "icons": ["sparkles", "play", "heart", "star", "bolt", "check", "arrow-right", "share"],
    "stickers": ["NEW", "SALE", "HOT", "LIMITED", "FREE", "OFFER", "TRENDING", "BUY NOW"],
}


PLANS = [
    {"id": "free", "name": "Free", "price_usd": 0, "credits": 100, "features": ["5 short videos / mo", "720p export", "Watermark", "Standard voices"]},
    {"id": "creator", "name": "Creator", "price_usd": 19, "credits": 1500, "features": ["50 videos / mo", "1080p export", "No watermark", "Premium voices", "Brand Kit"]},
    {"id": "studio", "name": "Studio", "price_usd": 49, "credits": 5000, "features": ["Unlimited drafts", "4K export", "All voices + cloning", "Team workspace", "Priority render"]},
    {"id": "enterprise", "name": "Enterprise", "price_usd": 199, "credits": 25000, "features": ["Custom avatars", "API access", "SSO", "Dedicated support", "SLAs"]},
]
